Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace HealthyMe.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CalorieTrackerController.cs
using HealthyMe.Areas.Identity.Data;
using HealthyMe.Models;
using HealthyMe.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using System.Security.Claims;

namespace HealthyMe.Controllers
{
    [Authorize]
    public class CalorieTrackerController : Controller
    {

        private readonly IHealthyMeRepository _repository;

        public CalorieTrackerController(IHealthyMeRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index(DateTime? date)
        {
            // Get all meals for the current user
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            

            // If date is not provided, default to today
            if (!date.HasValue)
            {
                date = DateTime.Today;
            }

            // Get all meals for the current user and specified date
            var meals = _repository.GetMealsByUserIdAndDate(userId, date.Value);

            // Create the ViewModel
            var viewModel = new List<MealViewModel>();

            foreach (var meal in meals)
            {
                // Get associated foods for each meal
                var foods = _repository.GetFoodsForMeal(meal.mealId);
                var MealItems = _repository.GetMealItems();
                // Create a ViewModel for each meal
                var mealViewModel = new MealViewModel
                {
                    Meal = meal,
                    Foods = foods,
                    MealItems = MealItems
                };

                viewModel.Add(mealViewModel);
            }

            return View(viewModel);
        }

        
        public IActionResult Delete(int id)
        {
            // Call the repository method to delete the food item
            _repository.DeleteFood(id);

            // Redirect to the index page or another appropriate page
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/NutritionController.cs
using HealthyMe.Areas.Identity.Data;
using HealthyMe.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using Newtonsoft.Json;

namespace HealthyMe.Controllers
{
    public class NutritionController : Controller
    {
        private readonly HttpClient _httpClient;
        private List<Food> _searchResultsList;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<NutritionController> _logger;
        private readonly IHealthyMeRepository _repository;
        private List<FoodNutritionModel> _foodNutritionModels;


        public NutritionController(IHttpClientFactory httpClientFactory,
            IHealthyMeRepository repository,
            UserManager<User> userManager,
            ILogger<NutritionController> logger)
        {

            _httpClient = httpClientFactory.CreateClient();
            _httpClient.BaseAddress = new Uri("https://api.nal.usda.gov/fdc/v1/");
            _httpClient.DefaultRequestHeaders.Add("Api-Key", "MumFCNVpvxfc8MGVIFXlcMHIKZw0BhNMzYBU7dBy");
            _searchResultsList = new List<Food>();


            _repository = repository;
            _userManager = userManager;
            _logger = logger;

        }
        public IActionResult Index()
        {
            return View(_searchResultsList);
        }
        public async Task<IActionResult> NutritionFoodSearch(string query)
        {
            try
            {


                var apiKey = "MumFCNVpvxfc8MGVIFXlcMHIKZw0BhNMzYBU7dBy";

                var response = await _httpClient.GetAsync($"foods/search?api_key={apiKey}&query={query}");
                response.EnsureSuccessStatusCode();

                var json = await response.Content.ReadAsStringAsync();
                var searchResults = JsonConvert.DeserializeObject<dynamic>(json);
                var searchResultsList = new List<Food>();



                foreach (var food in searchResults.foods)
                {
                    var result = new Food
                    {
                        FoodName = food.description,
                        FdcId = food.fdcId

                    };

                    searchResultsList.Add(result);
                }

                _searchResultsList = searchResultsList;

                return View("Index", _searchResultsList);
            }
            catch (HttpRequestException ex)
            {
                return StatusCode(500, "Internal server error");
            }
        }

        public async Task<IActionResult> GetNutritionDetails(int query)
        {
            try
            {

                _searchResultsList.Clear();

                var apiKey = "MumFCNVpvxfc8MGVIFXlcMHIKZw0BhNMzYBU7dBy";

                var response = await _httpClient.GetAsync($"food/{query}?api_key={apiKey}");
                response.EnsureSuccessStatusCode();

                var json = await response.Content.ReadAsStringAsync();
                var selectedFood = JsonConvert.DeserializeObject<dynamic>(json);

                

                    var result = new FoodNutritionModel
                    {
                        FoodName = selectedFood.description,
                        FdcId = selectedFood.fdcId,
                        Calories = GetNutrientValue(selectedFood.foodNutrients, "Energy"),
                        Protein = GetNutrientValue(selectedFood.foodNutrients, "Protein"),
                        Fat = GetNutrientValue(selectedFood.foodNutrients, "Total lipid (fat)"),
                        Carbs = GetNutrientValue(selectedFood.foodNutrients, "Carbohydrate, by difference"),
                        BrandName = selectedFood.brandName,
                        BrandedFoodCategory = selectedFood.brandedFoodCategory,
                        ServingSize = selectedFood.servingSize,
                        ServingSizeUnit = selectedFood.servingSizeUnit,
                        Ingredients = selectedFood.ingredients
                    };

                // Add only relevant nutrient values to the dictionary
                var relevantNutrientNames = new List<string>
                    {
                        "Sugars, total including NLEA",
                        "Fiber, total dietary",
                        "Calcium, Ca",
                        "Iron, Fe",
                        "Sodium, Na","Vitamin C, total ascorbic acid",
                        // Add other relevant nutrient names
                    };

                foreach (var nutrient in selectedFood.foodNutrients)
                {
                    var nutrientNameFromApi = (string)nutrient.nutrient.name;
                    var nutrientAmount = nutrient.amount;

                    // Check if the nutrient is relevant
                    if (relevantNutrientNames.Contains(nutrientNameFromApi))
                    {
                        result.AdditionalNutrients[nutrientNameFromApi] = nutrientAmount;
                    }
                }
                var searchResultsList = new List<FoodNutritionModel> { result };

                _foodNutritionModels = searchResultsList;

                return View("FoodDetailsView", searchResultsList);
            }
            catch (HttpRequestException ex)
            {
                _logger.LogError($"Error getting nutrition details: {ex.Message}");
                return StatusCode(500, "Internal server error");
            }
        }

        private decimal? GetNutrientValue(dynamic foodNutrients, string nutrientName)
        {
            foreach (var nutrient in foodNutrients)
            {
                // Access the nutrient property to get the nested nutrientName
                var nutrientNameFromApi = nutrient.nutrient.name;

                if (nutrientNameFromApi == nutrientName)
                {
                    return nutrient.amount;
                }
            }

            return null; // Nutrient not found
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthyMe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HealthyMe.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light text-white px-5 py-2">
            <div class="container ">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HealthyMe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CalorieTracker" asp-action="Index">Calorie Tracker</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nutrition" asp-action="Index">Nutrition</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AboutUs" asp-action="Index">About US</a>
                        </li>
                        
                        <li class="nav-item verticalLine">
                            <partial name="_Loginpartial" />
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div >
        <main role="main" >
            @RenderBody()
        </main>
    </div>
    <section>
        <footer class="footer">
            <p>&copy; 2023 HealthyMe. All rights reserved.</p>
        </footer>
    </section>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>